name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli@latest

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "EXPO_PUBLIC_API_URL=https://www.emuready.com" >> .env
          echo "EXPO_PUBLIC_ENV=development" >> .env
          echo "EXPO_PUBLIC_NAME=EmuReady" >> .env
          echo "EXPO_PUBLIC_VERSION=1.0.0" >> .env
          echo "EXPO_PUBLIC_BUILD_NUMBER=${{ github.run_number }}" >> .env
          echo "EXPO_PUBLIC_DEVELOPER=EmuReady Team" >> .env
          echo "EXPO_PUBLIC_SUPPORT_EMAIL=support@emuready.com" >> .env
          echo "EXPO_PUBLIC_PRIVACY_URL=https://emuready.com/privacy" >> .env
          echo "EXPO_PUBLIC_TERMS_URL=https://emuready.com/terms" >> .env

      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Rename APK with build info
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/emuready-app-build${BUILD_NUMBER}-${BRANCH_NAME}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: emuready-app-build-${{ github.run_number }}
          path: android/app/build/outputs/apk/release/emuready-app-*.apk
          retention-days: 30

      - name: Upload APK to release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/emuready-app-*.apk
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
